# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://end2endzone.github.io/"
DefaultContentLanguage  = "en"
title                   = "end2end zone"
theme                   = "end2endzone.hugo-future-imperfect-slim"
pagination.pagerSize    = 10
disqusShortname         = ""
pluralizeListTitles     = false
disableLanguages        = []

[services]
[services.googleAnalytics]
id = ""

enableRobotsTXT = true

# config.toml
[minify]
  # Set to false to disable HTML minification
  disableHTML = false

  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace      = true  # collapse all unnecessary whitespace
      keepConditionalComments = false
      keepDocumentTags    = true  # drop optional <html>, <head>, <body> tags
      keepEndTags         = true  # drop optional closing tags
      keepQuotes          = true  # drop quotes from attributes when safe

[markup]

  # https://gohugo.io/content-management/toc/
  # https://gohugo.io/getting-started/configuration-markup/#table-of-contents
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = true

  defaultMarkdownHandler = 'goldmark'
  
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
    
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true

    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true    # Allow raw HTML in Markdown files
      # `unsafe = true` is required to enable shortcode inside other shortcodes.
      # https://stackoverflow.com/questions/62129365/how-to-nest-shortcodes-with-hugo-raw-html-ommitted
      xhtml = false

  # https://www.brycewray.com/posts/2021/02/new-hugo-easier-writing/
  [markup.parser.attribute]
    block = true
    title = true
      
  # Disable Hugo's built-in syntax highlighting
  [markup.highlight]
    guessSyntax = false
    noClasses = false

    # Hugo uses [chroma](https://github.com/alecthomas/chroma) as a compile-time syntax highlighter by default.
    # To configure chroma, the following attributes are available:
    # (note that these attributes have no impact because the site is rendered with highlight.js which does client-side syntax highlighting)
    #
    # codeFences = true
    # hl_Lines = ""
    # lineNoStart = 1
    # lineNos = false
    # lineNumbersInTable = true
    # style = "monokai"
    # tabWidth = 4

  
[module]
  [module.hugoVersion]
  extended              = true
  min                   = "0.62.0"

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default", "css/end2endzone.css", "css/button.css"]
  jsFiles               = ["default", "js/linenumbers.js"]
  highlightjs           = true

  #highlightjsTheme      = "github-dark"
  #highlightjsTheme      = "stackoverflow-dark"
  #highlightjsTheme      = "androidstudio"
  highlightjsTheme      = "a11y-dark"

  highlightjsLang       = []

  highlightjsLineNos = false

  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = "vertical"
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "end2end zone"
    author              = "Antoine Beauchamp"
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "end2end zone"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "end2end zone"
    paragraph             = "My life dumped to a web site"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Hey that's me"

  [params.sidebar]
    about               = "Hey! I'm Antoine author of end2end zone. Take a couple of minutes to get to know me a little better."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = ""
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = ""
    theme               = "github-light"

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = ""
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "blog"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "categories"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "tags"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "contact"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.fr]
    LanguageCode        = "fr"
    LanguageName        = "Français"
    weight              = 2

    [Languages.fr.params.intro]
      header                = "end2end zone"
      paragraph             = "Ma vie posté en ligne."
      rssIntro              = true
      socialIntro           = true
      hideWhenSingleColumn  = false
      alwaysOnHomepage      = false

      [Languages.fr.params.intro.pic]
        src                 = "img/main/logo.jpg"
        shape               = "circle"
        width               = ""
        alt                 = "Hey that's me"

    [[Languages.fr.menu.main]]
      name              = "Accueil"
      identifier        = "home"
      url               = ""
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.fr.menu.main]]
      name              = "A Propos"
      identifier        = "about"
      url               = "about"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.fr.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "blog"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.fr.menu.main]]
      name              = "Catégories"
      identifier        = "categories"
      url               = "categories"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 4

    [[Languages.fr.menu.main]]
      name              = "Étiquettes"
      identifier        = "tags"
      url               = "tags"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.fr.menu.main]]
      name              = "Contact"
      identifier        = "contact"
      url               = "contact"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

    [Languages.fr.params.sidebar]
      about               = "Salut! Je suis Antoine auteur de end2end zone. Prenez quelques minutes pour mieux me connaître"
      postAmount          = 5
      categories          = true
      categoriesByCount   = true

[social]
  # Coding Communities
  github                = "end2endzone"
  gitlab                = ""
  stackoverflow         = "16481711" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = "154618444@N05"
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = "antoine.beauchamp.90"
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = ""
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = ""
