# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "http://www.end2endzone.com"
DefaultContentLanguage  = "en"
title                   = "end2end zone"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[module]
  [module.hugoVersion]
  extended              = true
  min                   = "0.62.0"

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = "horizontal"
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "end2end zone"
    author              = "Antoine Beauchamp"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Future Imperfect"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "end2end zone"
    paragraph             = "My life dumped to a web site"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Hey that's me"

  [params.sidebar]
    about               = "Hey I'm Antoine author of end2end zone. Take a couple of minutes to get to know me a little better."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = ""
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = ""
    theme               = "github-light"

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = ""
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "blog"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "categories"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "contact"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.fr]
    LanguageCode        = "fr"
    LanguageName        = "Français"
    title               = "end2end zone"
    description         = "Ma vie posté en ligne."
    weight              = 2

    [[Languages.fr.menu.main]]
      name              = "Accueil"
      identifier        = "home"
      url               = ""
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.fr.menu.main]]
      name              = "A Propos"
      identifier        = "about"
      url               = "about"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.fr.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "blog"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.fr.menu.main]]
      name              = "Catégories"
      identifier        = "categories"
      url               = "categories"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.fr.menu.main]]
      name              = "Contact"
      identifier        = "contact"
      url               = "contact"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

#  [Languages.pl]
#    LanguageCode        = "pl"
#    LanguageName        = "Polski"
#    title               = "Hugo Future Imperfect Slim po polsku"
#    description         = "Motyw HTML5 UP, przeniesiony przez Julio Pescadora i wzbogacony przez Patricka Collinsa. Wielojęzyczny przez StatnMap. Zasilany przez Hugo."
#    weight              = 2
#
#    [[Languages.pl.menu.main]]
#      name              = "Home"
#      identifier        = "home"
#      url               = ""
#      pre               = "<i class='fas fa-home'></i>"
#      weight            = 1
#
#    [[Languages.pl.menu.main]]
#      name              = "O mnie"
#      identifier        = "about"
#      url               = "about"
#      pre               = "<i class='far fa-id-card'></i>"
#      weight            = 2
#
#    [[Languages.pl.menu.main]]
#      name              = "Blog"
#      identifier        = "blog"
#      url               = "blog"
#      pre               = "<i class='far fa-newspaper'></i>"
#      weight            = 3
#
#    [[Languages.pl.menu.main]]
#      name              = "Kategorie"
#      identifier        = "categories"
#      url               = "categories"
#      pre               = "<i class='fas fa-sitemap'></i>"
#      weight            = 5
#
#    [[Languages.pl.menu.main]]
#      name              = "Kontakt"
#      identifier        = "contact"
#      url               = "contact"
#      pre               = "<i class='far fa-envelope'></i>"
#      weight            = 6
#
#  [Languages.pt]
#    LanguageCode        = "pt"
#    LanguageName        = "Português"
#    title               = "Hugo Future Imperfect Slim em português"
#    description         = "Um tema do HTML5 UP, portado por Julio Pescadora e reduzido por Patrick Collins. Multilíngue por StatnMap. Feito com Hugo."
#    weight              = 4
#
#    [[Languages.pt.menu.main]]
#      name              = "Início"
#      identifier        = "home"
#      url               = ""
#      pre               = "<i class='fas fa-home'></i>"
#      weight            = 1
#
#    [[Languages.pt.menu.main]]
#      name              = "Sobre"
#      identifier        = "about"
#      url               = "about"
#      pre               = "<i class='far fa-id-card'></i>"
#      weight            = 2
#
#    [[Languages.pt.menu.main]]
#      name              = "Blog"
#      identifier        = "blog"
#      url               = "blog"
#      pre               = "<i class='far fa-newspaper'></i>"
#      weight            = 3
#
#    [[Languages.pt.menu.main]]
#      name              = "Categorias"
#      identifier        = "categories"
#      url               = "categories"
#      pre               = "<i class='fas fa-sitemap'></i>"
#      weight            = 5
#
#    [[Languages.pt.menu.main]]
#      name              = "Contato"
#      identifier        = "contact"
#      url               = "contact"
#      pre               = "<i class='far fa-envelope'></i>"
#      weight            = 6
#
#  [Languages.de]
#    LanguageCode        = "de"
#    LanguageName        = "Deutsche"
#    weight              = 5
#
#  [Languages.es]
#    LanguageCode        = "es"
#    LanguageName        = "Española"
#    weight              = 6
#
#  [Languages.zh-CN]
#    LanguageCode        = "zh-CN"
#    LanguageName        = "中文 (简体)"
#    weight              = 7
#
#  [Languages.zh-TW]
#    LanguageCode        = "zh-TW"
#    LanguageName        = "中文 (正體)"
#    weight              = 8
#
#  [Languages.ja]
#    LanguageCode        = "ja"
#    LanguageName        = "日本語"
#    weight              = 9
#
#  [Languages.nl]
#    LanguageCode        = "nl"
#    LanguageName        = "Nederlands"
#    weight              = 10
#
#    [[Languages.nl.menu.main]]
#      name              = "Home"
#      identifier        = "home"
#      url               = ""
#      pre               = "<i class='fas fa-home'></i>"
#      weight            = 1
#
#    [[Languages.nl.menu.main]]
#      name              = "Over"
#      identifier        = "about"
#      url               = "about"
#      pre               = "<i class='far fa-id-card'></i>"
#      weight            = 2
#
#    [[Languages.nl.menu.main]]
#      name              = "Blog"
#      identifier        = "blog"
#      url               = "blog"
#      pre               = "<i class='far fa-newspaper'></i>"
#      weight            = 3
#
#    [[Languages.nl.menu.main]]
#      name              = "Categorieën"
#      identifier        = "categories"
#      url               = "categories"
#      pre               = "<i class='fas fa-sitemap'></i>"
#      weight            = 5
#
#    [[Languages.nl.menu.main]]
#      name              = "Contact"
#      identifier        = "contact"
#      url               = "contact"
#      pre               = "<i class='far fa-envelope'></i>"
#      weight            = 6

[social]
  # Coding Communities
  github                = "end2endzone"
  gitlab                = ""
  stackoverflow         = "16481711" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = "154618444@N05"
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = "antoine.beauchamp.90"
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = ""
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = ""
