name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your Hugo source
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We'll use a custom token below

      # Install Hugo extended v0.147.9
      - name: Setup Hugo extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.9'
          extended: true

      # Build the site
      - name: Build site
        run: ./ci/linux/build.sh

      # Ensure build output directory exists
      - name: Verify public directory
        run: |
          if [ ! -d public ]; then
            echo "ERROR: public/ directory not found. Hugo build failed."
            exit 1
          fi

      # Install dependency: lychee
      - name: Install lychee
        run: sudo ./ci/linux/install_lychee.sh

      # Check only internal links, fail on any broken link
      - name: Check internal links
        run: ./ci/linux/scan-local-links.sh

      # Check external links, emit warnings but don't fail
      - name: Check external links (warnings only)
        run: ./ci/linux/scan-external-links.sh

      # Checkout the deployment repo under current workspace (moved later to /tmp)
      # https://stackoverflow.com/questions/72360263/how-to-checkout-a-repository-outside-of-the-workspace-in-github-actions
      - name: Checkout end2endzone.github.io
        uses: actions/checkout@v3
        with:
          repository: end2endzone/end2endzone.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: tmp/end2endzone.github.io
          persist-credentials: false  # We'll use a custom token

      # Move previous checkout location.
      - name: Move end2endzone.github.io to /tmp/
        run: |
          ls -la
          echo 111
          ls -la tmp
          echo 222
          ls -la tmp/end2endzone.github.io
          echo 333
          mv tmp/end2endzone.github.io /tmp/end2endzone.github.io

      # Sync public/ to the deployment checkout (preserves .git)
      - name: Sync generated site to deployment repo
        run: |
          rsync -av --delete public/ /tmp/end2endzone.github.io/

      # Commit & push changes back to origin
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          cd /tmp/end2endzone.github.io
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/end2endzone/end2endzone.github.io.git
          git add -A
          if git diff-index --quiet HEAD; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Deploy updated site via GitHub Actions"
            git push origin HEAD:main
          fi
